import { Link } from 'react-router-dom';
import { FaQuoteLeft } from 'react-icons/fa';
import { useLang } from '../context/LanguageContext';

const englishParagraphs = [
  'Nepal has reached its present circumstances after passing through many ups and downs in political, economic, and social change. The political changes of 2007, 2046, 2063, and 2082 B.S. created new ideas, possibilities, and foundations for transformation in Nepali society. Yet political, economic, and social transformation has not advanced at the pace citizens expected, deepening challenges such as social fragmentation, political instability, economic disorder, and family disruption.',
  'These challenges cannot be resolved through the efforts of state institutions alone. Genuine change also requires citizens’ awareness, participation, unity, and shared responsibility. Therefore, it is essential that citizens organize against discrimination, injustice, inequality, violence, and unrest, and contribute to protecting rights, promoting equity, and establishing peace. Embracing this need, our social responsibility, and a firm resolve for change, Rights, Equity and Peace Campaign–Nepal was established with the motto “Respect in Equity, Life in Peace.”',
  'Established to make a positive contribution to human rights, women’s rights, children’s rights, the rights of persons with disabilities and senior citizens, juvenile justice, social justice, equality, reconciliation, mediation, and humanitarian service, this organization is firmly committed to conducting its activities in accordance with the Constitution and prevailing laws. Our central purpose is to strengthen the voices of individuals, classes, groups, victims, and citizens who have been left behind or deprived of rights, and to collaborate in building a just, equitable, and peaceful society.',
  'Taking into account the advice, suggestions, and guidance of distinguished members of society, concerned bodies, and well-wishers, the organization has been duly registered with the District Administration Office, Kathmandu. It has also affiliated with the Social Welfare Council and is proceeding after securing the required permissions from other relevant bodies. The organization has already begun activities in its areas of work in line with its objectives.',
  'We believe that social change is possible not through speeches and slogans alone, but through honest effort, shared responsibility, and continuous action. We are committed to advancing this campaign not as the effort of an individual or a group, but as a shared campaign of the whole society.',
  'I assure you that the organization’s journey ahead will be guided by the Constitution, prevailing laws, universal values, international law, human dignity, transparency, accountability, social responsibility, the rule of law, and ethical principles. Finally, we trust that your constructive advice, suggestions, support, cooperation, and guidance will give this campaign further energy and direction.',
];

const nepaliParagraphs = [
  'नेपालले राजनीतिक, आर्थिक तथा सामाजिक परिवर्तनका अनेकौँ आरोह–अवरोह पार गर्दै वर्तमान परिस्थितिमा आएको छ। वि.सं. २००७, २०४६, २०६३ तथा २०८२ का राजनीतिक परिवर्तनहरूले नेपाली समाजमा नयाँ सोच, सम्भावना र परिवर्तनका आधारहरू निर्माण गरेपनि नागरिकका अपेक्षा र चाहनाअनुरूप राजनीतिक, आर्थिक तथा सामाजिक रूपान्तरणले अपेक्षित गति लिन नसक्दा सामाजिक विखण्डन, राजनीतिक अस्थिरता, आर्थिक विशृङ्खलता र पारिवारिक विचलनजस्ता चुनौतीहरू अझै गहिरिँदै गएको अनुभूति भएको छ।',
  'यी समस्याहरूको समाधान राज्यका निकायहरूको मात्र प्रयासबाट सम्भव हुँदैन। परिवर्तनको वास्तविक आधार नागरिकको जागरूकता, सहभागिता, एकता र सामूहिक उत्तरदायित्वको पनि जरुरी छ। त्यसैले, समाजमा विद्यमान विभेद, अन्याय, असमानता, हिंसा र अशान्तिका विरुद्ध नागरिक तहबाट संगठित हुँदै अधिकारको संरक्षण, समताको प्रवर्द्धन र शान्तिको स्थापनाका लागि योगदान गर्नु आजको अपरिहार्य आवश्यकता हो। यही आवश्यकता, सामाजिक उत्तरदायित्व र परिवर्तनप्रतिको दृढ सङ्कल्पलाई आत्मसात् गर्दै ‘समतामा सम्मान शान्तिमा जीवन’ भन्ने मूल नारा बोकी ‘अधिकार, समता र शान्ति अभियान–नेपाल’ को जन्म भएको हो।',
  'मानव अधिकार, महिला अधिकार, बाल अधिकार, अपाङ्गता भएका व्यक्तिको अधिकार, जेष्ठ नागरिकको अधिकार, बाल न्याय, सामाजिक न्याय, समानता, मेलमिलाप, मध्यस्थता तथा मानवीय सेवाका क्षेत्रमा सकारात्मक योगदान पुर्‍याउने उद्देश्यले स्थापित यस संस्थाले संविधान र प्रचलित कानुनको अधीनमा रही आफ्ना गतिविधिहरू सञ्चालन गर्ने कुरामा दृढ छ। समाजका पछाडि परेका व्यक्ति, वर्ग, समूह, पीडित तथा अधिकारबाट वञ्चित नागरिकहरूको आवाजलाई सशक्त बनाउँदै न्यायपूर्ण, समतामूलक र शान्तिपूर्ण समाज निर्माणमा सहकार्य गर्नु हाम्रो मूल ध्येय हो।',
  'हामी विश्वास गर्छौँ, समाज परिवर्तन केवल भाषण र नाराबाट होइन, इमानदार प्रयास, साझा जिम्मेवारी र निरन्तर कर्मबाट सम्भव हुन्छ। त्यसैले, यस अभियानलाई कुनै व्यक्ति वा समूहको मात्र प्रयास नभई सम्पूर्ण समाजको साझा अभियानका रूपमा अघि बढाउने हाम्रो प्रतिबद्धता छ।',
];

const ChairpersonAppeal = () => {
  const { lang } = useLang();
  const english = lang === 'en';
  const paragraphs = english ? englishParagraphs : nepaliParagraphs;
  return <div><section className="bg-navy py-10 text-white"><div className="site-container"><p className="mb-2 text-sm text-white/60"><Link to="/" className="hover:text-white">{english ? 'Home' : 'गृह पृष्ठ'}</Link> <span className="px-1">/</span> <Link to="/about" className="hover:text-white">{english ? 'Our Organization' : 'हाम्रो संस्था'}</Link></p><h1 className={`text-2xl font-bold leading-relaxed md:text-3xl ${english ? '' : 'font-nepali'}`}>{english ? "The Chairperson's Message" : 'अध्यक्षको सन्देश'}</h1><div className="mt-3 h-1 w-12 rounded bg-sky" /></div></section><main className="bg-slate-50 px-4 py-10 sm:py-14"><article className="mx-auto max-w-4xl border border-slate-200 bg-white px-5 py-7 shadow-sm sm:px-10 sm:py-10"><FaQuoteLeft className="mb-5 text-sky/70" size={26} /><div className={`space-y-6 text-justify text-base leading-loose text-slate-700 sm:text-lg ${english ? '' : 'font-nepali'}`}>{paragraphs.map(p => <p key={p}>{p}</p>)}</div><div className={`mt-10 border-t-2 border-sky pt-6 text-navy ${english ? '' : 'font-nepali'}`}><p className="text-lg font-bold">{english ? 'Advocate Sushila Simkhada' : 'अधिवक्ता शुसिला सिंखडा'}</p><p className="mt-1">{english ? 'Chairperson' : 'अध्यक्ष'}</p><p>{english ? 'Rights, Equity and Peace Campaign–Nepal' : 'अधिकार, समता र शान्ति अभियान–नेपाल'}</p></div></article></main></div>;
};

export default ChairpersonAppeal;
